import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '@/lib/context/autoContext';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book your bus",
  description: "Generated by Karan with fun",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
